services:
  mongodb:
    image: mongo:6.0
    platform: linux/amd64
    container_name: box-inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: box_inventory

volumes:
  mongo_data:
