services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: box-inventory-api
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:5000}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      MongoDb__ConnectionString: ${MongoDb__ConnectionString:-mongodb://mongodb:27017}
      MongoDb__DatabaseName: ${MongoDb__DatabaseName:-box_inventory}
      Jwt__Authority: ${Jwt__Authority:-https://sso.allue.eu/realms/master}
      Jwt__Audience: ${Jwt__Audience:-account}
      Jwt__RequireHttpsMetadata: ${Jwt__RequireHttpsMetadata:-true}
      Cors__AllowedOrigins__0: ${Cors__AllowedOrigins__0:-*}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    platform: linux/amd64
    container_name: box-inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: box_inventory

volumes:
  mongo_data:
